package tuning

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/pg-sage/sidecar/internal/llm"
)

// The model's final answer: typed proposals only (owner decision 3),
// parsed defensively. Free SQL is not a proposal type; every executable
// statement is generated by pg_sage from the typed fields.

// ProposalType is what kind of change a proposal is.
type ProposalType string

// Proposal types.
const (
	ProposeIndexCreate ProposalType = "index_create"
	ProposeIndexDrop   ProposalType = "index_drop"
	ProposeGUC         ProposalType = "guc"
	ProposeReloption   ProposalType = "reloption"
	ProposeStatistics  ProposalType = "create_statistics"
	ProposeQueryHint   ProposalType = "query_hint"
)

// proposalTypes are the types in the order the packet lists them.
var proposalTypes = []ProposalType{ProposeIndexCreate, ProposeIndexDrop, ProposeGUC,
	ProposeReloption, ProposeStatistics, ProposeQueryHint}

// maxProposalsPerAnswer bounds what one answer may propose.
const maxProposalsPerAnswer = 8

// QueryID is a pg_stat_statements queryid. JSON numbers and decimal
// strings are read exactly (queryids use the whole int64 range, which a
// float64 would corrupt).
type QueryID int64

// UnmarshalJSON reads a number or a decimal string.
func (q *QueryID) UnmarshalJSON(raw []byte) error {
	s := strings.TrimSpace(string(raw))
	if unq, err := strconv.Unquote(s); err == nil {
		s = strings.TrimSpace(unq)
	}
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return fmt.Errorf("queryid %s is not an integer", string(raw))
	}
	*q = QueryID(v)
	return nil
}

// Proposal is one typed change the model proposes, with its rationale,
// the evidence it cites (S1, T1, F12, R3, ...) and its predicted effect
// in percent (negative: the metric falls).
type Proposal struct {
	Type              ProposalType `json:"type"`
	DDL               string       `json:"ddl,omitempty"`
	Index             string       `json:"index,omitempty"`
	Name              string       `json:"name,omitempty"`
	Value             string       `json:"value,omitempty"`
	Table             string       `json:"table,omitempty"`
	Option            string       `json:"option,omitempty"`
	Columns           []string     `json:"columns,omitempty"`
	Kinds             []string     `json:"kinds,omitempty"`
	QueryID           QueryID      `json:"queryid,omitempty"`
	Hint              string       `json:"hint,omitempty"`
	Rationale         string       `json:"rationale,omitempty"`
	Evidence          []string     `json:"evidence,omitempty"`
	ExpectedChangePct *float64     `json:"expected_change_pct,omitempty"`
	TargetQueryIDs    []QueryID    `json:"target_queryids,omitempty"`
}

// Answer is the model's final answer.
type Answer struct {
	Proposals []Proposal `json:"proposals"`
	Notes     string     `json:"notes,omitempty"`
}

// Answer errors.
var (
	ErrEmptyAnswer     = errors.New("tuning: the model's answer is empty")
	ErrMalformedAnswer = errors.New("tuning: the model's answer is not a proposal list")
)

// ParseAnswer reads an answer: a {"proposals": [...]} object or a bare
// proposal array, possibly fenced or after prose. Proposals beyond
// maxProposalsPerAnswer are dropped.
func ParseAnswer(raw string) (Answer, error) {
	if strings.TrimSpace(raw) == "" {
		return Answer{}, ErrEmptyAnswer
	}
	cleaned := strings.TrimSpace(llm.StripJSON(raw, llm.JSONAuto))
	if cleaned == "" {
		return Answer{}, fmt.Errorf("%w: no JSON found", ErrMalformedAnswer)
	}
	var a Answer
	var err error
	if strings.HasPrefix(cleaned, "[") {
		err = decodeStrict(cleaned, &a.Proposals)
	} else {
		err = decodeStrict(cleaned, &a)
	}
	if err != nil {
		return Answer{}, fmt.Errorf("%w: %v", ErrMalformedAnswer, err)
	}
	if len(a.Proposals) > maxProposalsPerAnswer {
		a.Proposals = a.Proposals[:maxProposalsPerAnswer]
	}
	return a, nil
}

// decodeStrict decodes exactly one JSON value into out (no repair of a
// truncated answer: half a proposal is not a proposal).
func decodeStrict(s string, out any) error {
	dec := json.NewDecoder(bytes.NewReader([]byte(s)))
	if err := dec.Decode(out); err != nil {
		return err
	}
	if dec.More() {
		return errors.New("trailing data after the answer")
	}
	return nil
}
