package cases

import (
	"fmt"
	"regexp"
	"strings"
)

func enrichDDLSafetyCandidate(
	f SourceFinding,
	candidate ActionCandidate,
) ActionCandidate {
	candidate.DDLPreflight = ddlPreflightFromFinding(f)
	candidate.ScriptOutput = scriptOutputFromFinding(f, candidate)
	if candidate.BlockedReason == "" && candidate.ActionType == "ddl_preflight" {
		candidate.BlockedReason = "direct execution blocked; generate PR or script"
	}
	return candidate
}

func ddlPreflightFromFinding(f SourceFinding) *DDLPreflightReport {
	d := f.Detail
	ruleID := detailString(d, "rule_id", f.RuleID)
	lockLevel := lockLevelForRule(ruleID)
	requiresRewrite := detailBool(d, "requires_rewrite",
		strings.Contains(ruleID, "rewrite"))
	riskScore := detailFloat(d, "risk_score", 0)
	table := detailString(d, "affected_table",
		detailString(d, "table_name", f.ObjectIdentifier))
	report := &DDLPreflightReport{
		Summary:         ddlPreflightSummary(lockLevel, requiresRewrite),
		RiskScore:       riskScore,
		LockLevel:       lockLevel,
		RequiresRewrite: requiresRewrite,
		TableName:       table,
		TableSizeBytes:  detailInt64(d, "table_size_bytes", 0),
		EstimatedRows:   detailInt64(d, "estimated_rows", 0),
		ActiveQueries:   int(detailInt64(d, "active_queries", 0)),
		PendingLocks:    int(detailInt64(d, "pending_locks", 0)),
		ReplicationLag:  detailFloat(d, "replication_lag", 0),
		EstimatedLockMs: detailInt64(d, "estimated_lock_ms", 0),
	}
	report.Checks = ddlPreflightChecks(report)
	return report
}

func ddlPreflightSummary(lockLevel string, rewrite bool) string {
	if rewrite {
		return fmt.Sprintf("%s rewrite risk", lockLevel)
	}
	return fmt.Sprintf("%s lock preflight", lockLevel)
}

func ddlPreflightChecks(r *DDLPreflightReport) []PreflightCheck {
	checks := []PreflightCheck{
		{Name: "lock_level", Status: checkStatus(r.LockLevel != ""),
			Detail: r.LockLevel},
		{Name: "rewrite", Status: rewriteStatus(r.RequiresRewrite),
			Detail: rewriteDetail(r.RequiresRewrite)},
		{Name: "activity", Status: activityStatus(r.ActiveQueries),
			Detail: fmt.Sprintf("%d active queries", r.ActiveQueries)},
		{Name: "pending_locks", Status: activityStatus(r.PendingLocks),
			Detail: fmt.Sprintf("%d pending locks", r.PendingLocks)},
		{Name: "replica_lag", Status: lagStatus(r.ReplicationLag),
			Detail: fmt.Sprintf("%.0fs", r.ReplicationLag)},
	}
	return checks
}

func checkStatus(ok bool) string {
	if ok {
		return "pass"
	}
	return "warn"
}

func rewriteStatus(rewrite bool) string {
	if rewrite {
		return "warn"
	}
	return "pass"
}

func rewriteDetail(rewrite bool) string {
	if rewrite {
		return "table rewrite likely"
	}
	return "metadata-only or concurrent path"
}

func activityStatus(value int) string {
	if value > 0 {
		return "warn"
	}
	return "pass"
}

func lagStatus(value float64) string {
	if value > 30 {
		return "warn"
	}
	return "pass"
}

func scriptOutputFromFinding(
	f SourceFinding,
	candidate ActionCandidate,
) *ScriptOutput {
	d := f.Detail
	sql := strings.TrimSpace(candidate.ProposedSQL)
	if sql == "" {
		sql = forwardFixScript(f)
	}
	return &ScriptOutput{
		Filename:        scriptFilename(f, candidate),
		MigrationSQL:    sql,
		RollbackSQL:     rollbackSQLForCandidate(candidate),
		VerificationSQL: verificationSQLForFinding(f, candidate),
		PRTitle:         prTitleForFinding(f),
		PRBody:          prBodyForFinding(f, candidate),
		RiskLabels:      riskLabelsForFinding(d, candidate),
		Format:          "sql",
	}
}

func forwardFixScript(f SourceFinding) string {
	safe := detailString(f.Detail, "safe_alternative", "")
	if safe == "" {
		safe = "Write an online, forward-fix migration for this DDL."
	}
	original := detailString(f.Detail, "original_sql", "")
	var b strings.Builder
	b.WriteString("-- Forward-fix migration plan generated by pg_sage\n")
	if original != "" {
		b.WriteString("-- Original unsafe DDL:\n-- ")
		b.WriteString(original)
		b.WriteString("\n")
	}
	b.WriteString("-- Safe rollout plan:\n")
	b.WriteString("-- ")
	b.WriteString(strings.ReplaceAll(safe, "\n", "\n-- "))
	b.WriteString("\n")
	return b.String()
}

func scriptFilename(f SourceFinding, candidate ActionCandidate) string {
	id := strings.TrimSpace(f.ID)
	if id == "" {
		id = "case"
	}
	action := strings.TrimSpace(candidate.ActionType)
	if action == "" {
		action = "ddl_preflight"
	}
	return id + "_" + action + ".sql"
}

func rollbackSQLForCandidate(candidate ActionCandidate) string {
	if candidate.RollbackClass != "reversible" {
		return ""
	}
	sql := strings.TrimSpace(candidate.ProposedSQL)
	if strings.HasPrefix(strings.ToUpper(sql), "CREATE INDEX CONCURRENTLY ") {
		if name := indexNameFromCreateIndex(sql); name != "" {
			return "DROP INDEX CONCURRENTLY " + name + ";"
		}
	}
	if strings.HasPrefix(strings.ToUpper(sql), "DROP INDEX CONCURRENTLY ") {
		return "-- Recreate the dropped index from version control."
	}
	return ""
}

func indexNameFromCreateIndex(sql string) string {
	re := regexp.MustCompile(`(?i)CREATE\s+(?:UNIQUE\s+)?INDEX\s+CONCURRENTLY\s+([^\s]+)`)
	matches := re.FindStringSubmatch(sql)
	if len(matches) < 2 {
		return ""
	}
	return strings.Trim(matches[1], `";`)
}

func verificationSQLForFinding(
	f SourceFinding,
	candidate ActionCandidate,
) []string {
	switch candidate.ActionType {
	case "create_index_concurrently":
		if name := indexNameFromCreateIndex(candidate.ProposedSQL); name != "" {
			return []string{
				"SELECT indisvalid, indisready FROM pg_index WHERE indexrelid = '" +
					name + "'::regclass;",
				"EXPLAIN " + detailString(f.Detail, "sample_query",
					"-- rerun affected query"),
			}
		}
	case "drop_unused_index":
		return []string{
			"SELECT to_regclass('" + f.ObjectIdentifier + "');",
			"-- Confirm application error rate and query latency stay normal.",
		}
	}
	return []string{
		"-- Verify catalog shape matches the intended migration outcome.",
		"-- Rerun pg_sage analyzers and confirm the case no longer fires.",
	}
}

func prTitleForFinding(f SourceFinding) string {
	if f.Title != "" {
		return "Review DDL safety plan: " + f.Title
	}
	return "Review DDL safety plan"
}

func prBodyForFinding(f SourceFinding, candidate ActionCandidate) string {
	rollback := candidate.RollbackClass
	if rollback == "" {
		rollback = "unknown"
	}
	return fmt.Sprintf(
		"Generated from pg_sage case %s. Risk tier: %s. Rollback class: %s.",
		f.ID, candidate.RiskTier, rollback,
	)
}

func riskLabelsForFinding(
	detail map[string]any,
	candidate ActionCandidate,
) []string {
	labels := []string{candidate.RiskTier, candidate.RollbackClass}
	if rule := detailString(detail, "rule_id", ""); rule != "" {
		labels = append(labels, rule)
	}
	return labels
}

func lockLevelForRule(ruleID string) string {
	switch {
	case strings.Contains(ruleID, "index_not_concurrent"):
		return "SHARE"
	case strings.Contains(ruleID, "constraint_not_valid"):
		return "SHARE ROW EXCLUSIVE"
	default:
		return "ACCESS EXCLUSIVE"
	}
}

func detailString(detail map[string]any, key, fallback string) string {
	if detail == nil {
		return fallback
	}
	if v, ok := detail[key].(string); ok && v != "" {
		return v
	}
	return fallback
}

func detailBool(detail map[string]any, key string, fallback bool) bool {
	if detail == nil {
		return fallback
	}
	if v, ok := detail[key].(bool); ok {
		return v
	}
	return fallback
}

func detailFloat(detail map[string]any, key string, fallback float64) float64 {
	if detail == nil {
		return fallback
	}
	switch v := detail[key].(type) {
	case float64:
		return v
	case float32:
		return float64(v)
	case int:
		return float64(v)
	case int64:
		return float64(v)
	default:
		return fallback
	}
}

func detailInt64(detail map[string]any, key string, fallback int64) int64 {
	if detail == nil {
		return fallback
	}
	switch v := detail[key].(type) {
	case int64:
		return v
	case int:
		return int64(v)
	case float64:
		return int64(v)
	default:
		return fallback
	}
}
