package cases

import (
	"strings"
	"time"
)

func vacuumAutopilotCandidate(f SourceFinding) (ActionCandidate, bool) {
	switch f.Category {
	case "table_bloat", "schema_lint:lint_bloated_table":
		return tableBloatCandidate(f), true
	case "xid_wraparound", "schema_lint:lint_txid_age",
		"schema_lint:lint_mxid_age":
		return freezeDiagnosticCandidate(f), true
	case "vacuum_tuning":
		return autovacuumTuningCandidate(f), true
	case "bloat_remediation":
		return bloatRemediationCandidate(f), true
	case "reindex_candidate":
		return reindexCandidate(f), true
	case "blocked_vacuum":
		return blockedVacuumCandidate(f), true
	default:
		return ActionCandidate{}, false
	}
}

func bloatRemediationCandidate(f SourceFinding) ActionCandidate {
	expires := time.Now().UTC().Add(7 * 24 * time.Hour)
	candidate := ActionCandidate{
		ActionType:       "plan_bloat_remediation",
		RiskTier:         "high",
		Confidence:       0.70,
		ExpiresAt:        &expires,
		OutputModes:      []string{"generate_pr_or_script"},
		RollbackClass:    "forward_fix_only",
		VerificationPlan: verificationPlanForAction("plan_bloat_remediation"),
		BlockedReason:    "bloat remediation requires reviewed online rebuild plan",
	}
	candidate.ScriptOutput = bloatRemediationScriptOutput(f, candidate)
	return candidate
}

func reindexCandidate(f SourceFinding) ActionCandidate {
	sql := strings.TrimSpace(f.RecommendedSQL)
	if sql == "" {
		sql = "REINDEX INDEX CONCURRENTLY " + f.ObjectIdentifier + ";"
	}
	expires := time.Now().UTC().Add(72 * time.Hour)
	return ActionCandidate{
		ActionType:       "reindex_concurrently",
		RiskTier:         "moderate",
		Confidence:       0.72,
		ProposedSQL:      sql,
		ExpiresAt:        &expires,
		OutputModes:      []string{"queue_for_approval", "generate_pr_or_script"},
		RollbackClass:    "reversible",
		VerificationPlan: verificationPlanForAction("reindex_concurrently"),
	}
}

func blockedVacuumCandidate(f SourceFinding) ActionCandidate {
	expires := time.Now().UTC().Add(30 * time.Minute)
	return ActionCandidate{
		ActionType:       "diagnose_vacuum_pressure",
		RiskTier:         "safe",
		Confidence:       0.80,
		ProposedSQL:      diagnoseVacuumPressureSQL(f.ObjectIdentifier),
		ExpiresAt:        &expires,
		OutputModes:      []string{"execute", "script"},
		RollbackClass:    "not_applicable",
		VerificationPlan: verificationPlanForAction("diagnose_vacuum_pressure"),
	}
}

func bloatRemediationScriptOutput(
	f SourceFinding,
	candidate ActionCandidate,
) *ScriptOutput {
	table := f.ObjectIdentifier
	return &ScriptOutput{
		Filename: "bloat_remediation_" + sanitizeScriptPart(table) + ".sql",
		MigrationSQL: "-- Online bloat remediation plan generated by pg_sage\n" +
			"-- Prefer pg_repack or a reviewed online rebuild for " + table + ".\n" +
			"-- Avoid VACUUM FULL unless a maintenance outage is approved.\n",
		VerificationSQL: []string{
			"SELECT pg_total_relation_size('" + table + "'::regclass);",
			"-- Rerun bloat analyzer and confirm bloat ratio decreases.",
		},
		PRTitle: "Review bloat remediation plan: " + table,
		PRBody: "Generated from pg_sage case " + f.ID +
			". Risk tier: " + candidate.RiskTier + ".",
		RiskLabels: []string{"high", "forward_fix_only", "bloat_remediation"},
		Format:     "sql",
	}
}

func tableBloatCandidate(f SourceFinding) ActionCandidate {
	sql := strings.TrimSpace(f.RecommendedSQL)
	if sql == "" {
		sql = "VACUUM " + f.ObjectIdentifier + ";"
	}
	expires := time.Now().UTC().Add(24 * time.Hour)
	candidate := ActionCandidate{
		ActionType:       "vacuum_table",
		RiskTier:         "safe",
		Confidence:       0.74,
		ProposedSQL:      sql,
		ExpiresAt:        &expires,
		OutputModes:      []string{"execute", "queue_for_approval", "generate_pr_or_script"},
		RollbackClass:    "no_rollback_needed",
		VerificationPlan: verificationPlanForAction("vacuum_table"),
	}
	if detailBool(f.Detail, "io_saturated", false) {
		candidate.BlockedReason = "IO is saturated; wait for maintenance window or lower load"
		candidate.OutputModes = []string{"generate_pr_or_script"}
	}
	return candidate
}

func freezeDiagnosticCandidate(f SourceFinding) ActionCandidate {
	expires := time.Now().UTC().Add(30 * time.Minute)
	return ActionCandidate{
		ActionType:       "diagnose_freeze_blockers",
		RiskTier:         "safe",
		Confidence:       0.78,
		ProposedSQL:      diagnoseFreezeBlockersSQL(),
		ExpiresAt:        &expires,
		OutputModes:      []string{"execute", "script"},
		RollbackClass:    "not_applicable",
		VerificationPlan: verificationPlanForAction("diagnose_freeze_blockers"),
	}
}

func autovacuumTuningCandidate(f SourceFinding) ActionCandidate {
	sql := strings.TrimSpace(f.RecommendedSQL)
	expires := time.Now().UTC().Add(72 * time.Hour)
	candidate := ActionCandidate{
		ActionType:       "set_table_autovacuum",
		RiskTier:         "moderate",
		Confidence:       0.72,
		ProposedSQL:      sql,
		ExpiresAt:        &expires,
		OutputModes:      []string{"queue_for_approval", "generate_pr_or_script"},
		RollbackClass:    "forward_fix_only",
		VerificationPlan: verificationPlanForAction("set_table_autovacuum"),
	}
	candidate.ScriptOutput = scriptOutputFromFinding(f, candidate)
	return candidate
}

func diagnoseFreezeBlockersSQL() string {
	return `SELECT datname,
       age(datfrozenxid) AS database_xid_age
FROM pg_database
ORDER BY database_xid_age DESC;

SELECT pid,
       usename,
       application_name,
       backend_xmin,
       age(backend_xmin) AS xmin_age,
       state,
       now() - xact_start AS transaction_age,
       left(query, 1000) AS query
FROM pg_stat_activity
WHERE backend_xmin IS NOT NULL
ORDER BY age(backend_xmin) DESC
LIMIT 20;`
}

func diagnoseVacuumPressureSQL(table string) string {
	tableFilter := ""
	if strings.TrimSpace(table) != "" {
		tableFilter = "WHERE relid = '" + table + "'::regclass"
	}
	return `SELECT schemaname,
       relname,
       n_dead_tup,
       last_vacuum,
       last_autovacuum,
       vacuum_count,
       autovacuum_count
FROM pg_stat_user_tables
` + tableFilter + `;

SELECT pid,
       backend_xmin,
       age(backend_xmin) AS xmin_age,
       state,
       now() - xact_start AS transaction_age,
       left(query, 1000) AS query
FROM pg_stat_activity
WHERE backend_xmin IS NOT NULL
ORDER BY age(backend_xmin) DESC
LIMIT 20;`
}
