package firstlook

import (
	"context"
	"encoding/json"
	"reflect"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// The sequence read was rewritten so its plan no longer depends on
// pg_depend's row estimates (a stale catalog took 11-14 s at 5,000
// sequences). legacySequencesSQL is the query it replaced, verbatim: the
// new read must return exactly its rows.
//
// No invalid-input or concurrency tests: the read takes only its row bound
// and runs in one read-only transaction with no shared Go state.
const legacySequencesSQL = tag + `SELECT s.schemaname::text, s.sequencename::text, s.last_value,
  s.min_value, s.max_value, s.increment_by, s.cycle,
  pg_catalog.has_sequence_privilege(sc.oid, 'SELECT,USAGE'),
  COALESCE(col.name, ''), COALESCE(col.type, '')
FROM pg_catalog.pg_sequences s
JOIN pg_catalog.pg_namespace n ON n.nspname = s.schemaname
JOIN pg_catalog.pg_class sc ON sc.relnamespace = n.oid AND sc.relname = s.sequencename
LEFT JOIN LATERAL (
  SELECT dn.nspname::text || '.' || dt.relname::text || '.' || a.attname::text AS name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS type
  FROM (SELECT d.refobjid AS relid, d.refobjsubid AS attnum FROM pg_catalog.pg_depend d
        WHERE d.classid = 'pg_catalog.pg_class'::regclass AND d.objid = sc.oid
          AND d.refclassid = 'pg_catalog.pg_class'::regclass
          AND d.deptype IN ('a', 'i') AND d.refobjsubid > 0
        UNION
        SELECT ad.adrelid, ad.adnum FROM pg_catalog.pg_depend d
        JOIN pg_catalog.pg_attrdef ad ON ad.oid = d.objid
        WHERE d.classid = 'pg_catalog.pg_attrdef'::regclass
          AND d.refclassid = 'pg_catalog.pg_class'::regclass AND d.refobjid = sc.oid
          AND d.deptype = 'n') u
  JOIN pg_catalog.pg_attribute a ON a.attrelid = u.relid AND a.attnum = u.attnum
    AND NOT a.attisdropped
  JOIN pg_catalog.pg_class dt ON dt.oid = u.relid
  JOIN pg_catalog.pg_namespace dn ON dn.oid = dt.relnamespace
  ORDER BY CASE a.atttypid WHEN 'pg_catalog.int2'::regtype THEN 1
    WHEN 'pg_catalog.int4'::regtype THEN 2 WHEN 'pg_catalog.int8'::regtype THEN 3
    ELSE 4 END, 1
  LIMIT 1) col ON true
WHERE ` + userSchemas + `
ORDER BY 1, 2
LIMIT $1`

// seedSequenceZoo creates every way a sequence relates to a column: serial,
// smallserial and bigserial, identity (always and by default), OWNED BY,
// DEFAULT only (also across schemas, where the narrowest column sorts last
// by name), a numeric DEFAULT, a dropped column,
// a type tie broken by name, and unowned sequences used and never used.
// The main schema and several objects have quoted names. It returns the
// main schema and the other one.
func seedSequenceZoo(t *testing.T, ctx context.Context, pool *pgxpool.Pool) (string, string) {
	t.Helper()
	other := seedSchema(t, ctx, pool, "fl_seqeq_other_",
		"CREATE SEQUENCE {s}.cross_seq AS bigint",
		"CREATE TABLE {s}.wide (id bigint DEFAULT nextval('{s}.cross_seq'))",
		"ALTER SEQUENCE {s}.cross_seq OWNED BY {s}.wide.id",
		"SELECT setval('{s}.cross_seq', 40000)")
	o := pgx.Identifier{other}.Sanitize()
	main := seedSchema(t, ctx, pool, `fl Seq"Eq_`,
		`CREATE TABLE {s}."Serial Tbl" ("Order ID" serial, big bigserial, small smallserial)`,
		`SELECT setval('{s}."Serial Tbl_Order ID_seq"', 1000)`,
		`CREATE TABLE {s}.ident (a int GENERATED ALWAYS AS IDENTITY,
		  b bigint GENERATED BY DEFAULT AS IDENTITY (START 100))`,
		"INSERT INTO {s}.ident DEFAULT VALUES",
		`CREATE SEQUENCE {s}."Owned Seq" AS bigint`,
		"CREATE TABLE {s}.owner_tbl (id int)",
		`ALTER SEQUENCE {s}."Owned Seq" OWNED BY {s}.owner_tbl.id`,
		`SELECT setval('{s}."Owned Seq"', 2000000000)`,
		"CREATE SEQUENCE {s}.unused_seq",
		`CREATE SEQUENCE {s}.used_seq INCREMENT -2 MINVALUE -1000 MAXVALUE 0 START -1 CYCLE`,
		"SELECT nextval('{s}.used_seq')",
		"CREATE TABLE {s}.aa_wide (id bigint DEFAULT nextval('"+o+".cross_seq'))",
		"CREATE TABLE {s}.zz_narrow (id smallint DEFAULT nextval('"+o+".cross_seq'))",
		"CREATE SEQUENCE {s}.num_seq",
		"CREATE TABLE {s}.numtab (n numeric DEFAULT nextval('{s}.num_seq'), m text)",
		"SELECT setval('{s}.num_seq', 9)",
		"CREATE SEQUENCE {s}.drop_seq",
		"CREATE TABLE {s}.droptab (keep int, gone int DEFAULT nextval('{s}.drop_seq'))",
		"ALTER TABLE {s}.droptab DROP COLUMN gone",
		"SELECT setval('{s}.drop_seq', 3)",
		"CREATE SEQUENCE {s}.tie_seq",
		"CREATE TABLE {s}.zeta (id int DEFAULT nextval('{s}.tie_seq'))",
		"CREATE TABLE {s}.alpha (id int DEFAULT nextval('{s}.tie_seq'))",
		"SELECT setval('{s}.tie_seq', 5)")
	return main, other
}

// rawSequenceRows runs one sequence query and keeps the rows of schemas.
// Both queries of a comparison run in one repeatable-read transaction so
// they see the same catalog.
func rawSequenceRows(t *testing.T, ctx context.Context, tx pgx.Tx, sql string,
	schemas ...string) [][]any {
	t.Helper()
	keep := map[string]bool{}
	for _, s := range schemas {
		keep[s] = true
	}
	rows, err := tx.Query(ctx, sql, maxSequenceRows)
	if err != nil {
		t.Fatalf("query sequences: %v", err)
	}
	defer rows.Close()
	var out [][]any
	for rows.Next() {
		v, err := rows.Values()
		if err != nil {
			t.Fatalf("row values: %v", err)
		}
		if s, ok := v[0].(string); ok && keep[s] {
			out = append(out, v)
		}
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("read sequences: %v", err)
	}
	return out
}

// compareSequenceReads returns the new read's rows after requiring the
// legacy query to return exactly the same ones, in the same order.
func compareSequenceReads(t *testing.T, ctx context.Context, pool *pgxpool.Pool,
	schemas ...string) map[string][]any {
	t.Helper()
	tx, err := pool.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.RepeatableRead,
		AccessMode: pgx.ReadOnly})
	if err != nil {
		t.Fatalf("begin: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	got := rawSequenceRows(t, ctx, tx, sequencesSQL, schemas...)
	want := rawSequenceRows(t, ctx, tx, legacySequencesSQL, schemas...)
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("sequence read differs from the legacy query:\n got %v\nwant %v", got, want)
	}
	byName := map[string][]any{}
	for _, r := range got {
		byName[r[0].(string)+"."+r[1].(string)] = r
	}
	return byName
}

// wantOwner requires the row of sequence name to name column (and type),
// or no column when column is empty.
func wantOwner(t *testing.T, rows map[string][]any, name, column, typ string) {
	t.Helper()
	r, ok := rows[name]
	if !ok {
		t.Fatalf("sequence %s missing from %v", name, rows)
	}
	if r[8] != column || r[9] != typ {
		t.Errorf("sequence %s feeds %v (%v), want %q (%q)", name, r[8], r[9], column, typ)
	}
}

func TestSequencesSQLMatchesLegacyQuery(t *testing.T) {
	pool, ctx := livePool(t)
	s, o := seedSequenceZoo(t, ctx, pool)
	rows := compareSequenceReads(t, ctx, pool, s, o)
	if len(rows) != 12 {
		t.Fatalf("%d fixture sequences, want 12: %v", len(rows), rows)
	}
	wantOwner(t, rows, s+".Serial Tbl_Order ID_seq", s+".Serial Tbl.Order ID", "integer")
	wantOwner(t, rows, s+".Serial Tbl_big_seq", s+".Serial Tbl.big", "bigint")
	wantOwner(t, rows, s+".Serial Tbl_small_seq", s+".Serial Tbl.small", "smallint")
	wantOwner(t, rows, s+".ident_a_seq", s+".ident.a", "integer")
	wantOwner(t, rows, s+".ident_b_seq", s+".ident.b", "bigint")
	wantOwner(t, rows, s+".Owned Seq", s+".owner_tbl.id", "integer")
	wantOwner(t, rows, s+".unused_seq", "", "")
	wantOwner(t, rows, s+".used_seq", "", "")
	wantOwner(t, rows, o+".cross_seq", s+".zz_narrow.id", "smallint")
	wantOwner(t, rows, s+".num_seq", s+".numtab.n", "numeric")
	wantOwner(t, rows, s+".drop_seq", "", "")
	wantOwner(t, rows, s+".tie_seq", s+".alpha.id", "integer")
	used := rows[s+".used_seq"]
	want := []any{int64(-1), int64(-1000), int64(0), int64(-2), true, true}
	if !reflect.DeepEqual(used[2:8], want) {
		t.Errorf("used_seq values = %v, want %v", used[2:8], want)
	}
	if unused := rows[s+".unused_seq"]; unused[2] != nil || unused[7] != true {
		t.Errorf("unused_seq = %v, want a NULL last_value the role may read", unused)
	}
}

// Without privileges on the sequences every last_value is NULL and the
// privilege column says why; the columns still resolve from the catalog.
func TestSequencesSQLMatchesLegacyQueryWithoutPrivileges(t *testing.T) {
	admin, ctx := livePool(t)
	s, o := seedSequenceZoo(t, ctx, admin)
	mon := monitorRole(t, ctx, admin)
	rows := compareSequenceReads(t, ctx, mon, s, o)
	if len(rows) != 12 {
		t.Fatalf("%d fixture sequences as monitor, want 12", len(rows))
	}
	for name, r := range rows {
		if r[2] != nil || r[7] != false {
			t.Errorf("%s as monitor: last_value %v readable %v, want NULL and false",
				name, r[2], r[7])
		}
	}
	wantOwner(t, rows, o+".cross_seq", s+".zz_narrow.id", "smallint")
	wantOwner(t, rows, s+".Owned Seq", s+".owner_tbl.id", "integer")
}

// An empty selection is not an error: a schema without sequences returns
// no rows from either query.
func TestSequencesSQLEmptySchemaMatchesLegacyQuery(t *testing.T) {
	pool, ctx := livePool(t)
	s := seedSchema(t, ctx, pool, "fl_seqeq_empty_", "CREATE TABLE {s}.plain (v text)")
	if rows := compareSequenceReads(t, ctx, pool, s); len(rows) != 0 {
		t.Fatalf("rows = %v, want none", rows)
	}
}

// planNode is the part of EXPLAIN (FORMAT JSON) the plan guard reads.
type planNode struct {
	NodeType  string     `json:"Node Type"`
	Relation  string     `json:"Relation Name"`
	IndexCond string     `json:"Index Cond"`
	Plans     []planNode `json:"Plans"`
}

// dependScans returns every pg_depend access with the index condition
// that drives it (a bitmap heap scan's comes from its index scan child).
func dependScans(n planNode, out []planNode) []planNode {
	if n.Relation == "pg_depend" {
		x := n
		if n.NodeType == "Bitmap Heap Scan" && len(n.Plans) == 1 {
			x.IndexCond = n.Plans[0].IndexCond
		}
		out = append(out, x)
	}
	for _, c := range n.Plans {
		out = dependScans(c, out)
	}
	return out
}

// Every pg_depend lookup is keyed by the sequence (objid or refobjid), so
// row estimates cannot turn it into a scan of every dependency per
// sequence (the stale-catalog plan read pg_depend by classid alone).
func TestSequencesSQLKeysEveryDependLookup(t *testing.T) {
	pool, ctx := livePool(t)
	seedSequenceZoo(t, ctx, pool)
	var raw string
	if err := pool.QueryRow(ctx, "EXPLAIN (FORMAT JSON) "+sequencesSQL,
		maxSequenceRows).Scan(&raw); err != nil {
		t.Fatalf("explain: %v", err)
	}
	var plans []struct {
		Plan planNode `json:"Plan"`
	}
	if err := json.Unmarshal([]byte(raw), &plans); err != nil || len(plans) != 1 {
		t.Fatalf("decode plan (%v): %s", err, raw)
	}
	scans := dependScans(plans[0].Plan, nil)
	if len(scans) != 2 {
		t.Fatalf("%d pg_depend accesses, want 2 (owner and DEFAULT): %s", len(scans), raw)
	}
	for _, s := range scans {
		if !strings.Contains(s.IndexCond, "objid = ") {
			t.Errorf("pg_depend %s with condition %q is not keyed by the sequence",
				s.NodeType, s.IndexCond)
		}
	}
}
